console.log("The major planets of the solar system are:")
console.log("Mercury")
console.log("Venus")
console.log("Earth")
console.log("Mars")
console.log("Jupiter")
console.log("Saturn")
console.log("Uranus")
console.log("Neptune")